version: "3.3"

services:
  postgres:
    image: postgres
    volumes:
     - /opt/postgres:/var/lib/pgsql
    restart: always
    hostname: 'nc-postgres'
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd

  nextcloud:
    image: nextcloud
    volumes:
      - /opt/nextcloud:/var/www/html
    ports:
      - "8088:80"
    restart: always
    environment:
      POSTGRES_HOST: nc-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: nextcloud


















