---
- hosts: Ubuntu
  become: true
  tasks:
   - name: packages
     apt:
      update_cache: yes
      name: 
       - apache2
       - mysql-server
       - python3-pymysql
       - php
       - php-mysql
       - libapache2-mod-php
       - git
      state: latest
   - name: changeroot
     community.mysql.mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: 'root'
      password: 'P@ssw0rd'
      state: present

- hosts: Centos
  become: true
  tasks:
   - name: packages
     yum:
      update_cache: yes
      name:
       - httpd
       - mariadb-server
       - mariadb
       - python3-PyMySQL
       - php
       - php-mysqlnd
       - git
      state: latest
   - name: restart
     ansible.builtin.service:
      name: mariadb
      state: restarted
      enabled: yes
   - name: changeroot
     community.mysql.mysql_user:
      name: root
      password: P@ssw0rd   


